# Autogenerated to silence R CMD check NOTES for NSE variables.
rlang::.data
utils::globalVariables(c(
  "Count","BgRatio","GeneRatio","score","Description","P","generatio","geneS",
  "group","individual","value","sep","sep_n","boundary","block_id","n_blocks",
  "id","start","end","num","title","genenum","hjust","set","case",
  "region","sum_length","n","mean_gain","y","tree"
))

